{
	"symbols" : [
		{ "id" : 0, "code" : "WILD", "wild" : true},
		{"id" : 1, "code" : "SYMBOL_1"},
		{"id" : 2, "code" : "SYMBOL_2"},
		{"id" : 3, "code" : "SYMBOL_3"},
		{"id" : 4, "code" : "SYMBOL_4"},
		{"id" : 5, "code" : "SYMBOL_5"},
		{"id" : 6, "code" : "SYMBOL_6"},
		{"id" : 7, "code" : "SYMBOL_7"},
		{"id" : 8, "code" : "SYMBOL_8"},
		{"id" : 9, "code" : "SYMBOL_0"},
		{"id" : 10, "code" : "SCATTER"}
	],
	
	"payoutCombos" : [
	      {"id" : 0, "symbol" : 1, "occurrence" : 5, "win" : 500},              
	      {"id" : 1, "symbol" : 1, "occurrence" : 4, "win" : 30},                 
	      {"id" : 2, "symbol" : 1, "occurrence" : 3, "win" : 10},                 
	      {"id" : 3, "symbol" : 1, "occurrence" : 2, "win" : 2},                 
	      {"id" : 4, "symbol" : 2, "occurrence" : 5, "win" : 250},                 
	      {"id" : 5, "symbol" : 2, "occurrence" : 4, "win" : 30},                 
	      {"id" : 6, "symbol" : 2, "occurrence" : 3, "win" : 10},                 
	      {"id" : 7, "symbol" : 2, "occurrence" : 2, "win" : 2},                 
	      {"id" : 8, "symbol" : 3, "occurrence" : 5, "win" : 250},                 
	      {"id" : 9, "symbol" : 3, "occurrence" : 4, "win" : 30},                 
	      {"id" : 10, "symbol" : 3, "occurrence" : 3, "win" : 10},                 
	      {"id" : 11, "symbol" : 3, "occurrence" : 2, "win" : 2},                 
	      {"id" : 12, "symbol" : 4, "occurrence" : 5, "win" : 100},                 
	      {"id" : 13, "symbol" : 4, "occurrence" : 4, "win" : 20},                 
	      {"id" : 14, "symbol" : 4, "occurrence" : 3, "win" : 10},                 
	      {"id" : 15, "symbol" : 5, "occurrence" : 5, "win" : 75},                 
	      {"id" : 16, "symbol" : 5, "occurrence" : 4, "win" : 20},                 
	      {"id" : 17, "symbol" : 5, "occurrence" : 3, "win" : 10},                 
	      {"id" : 18, "symbol" : 6, "occurrence" : 5, "win" : 50},                 
	      {"id" : 19, "symbol" : 6, "occurrence" : 4, "win" : 20},                 
	      {"id" : 20, "symbol" : 6, "occurrence" : 3, "win" : 10},                 
	      {"id" : 21, "symbol" : 7, "occurrence" : 5, "win" : 30},                 
	      {"id" : 22, "symbol" : 7, "occurrence" : 4, "win" : 10},                
	      {"id" : 23, "symbol" : 7, "occurrence" : 3, "win" : 5},                 
	      {"id" : 24, "symbol" : 8, "occurrence" : 5, "win" : 30},                 
	      {"id" : 25, "symbol" : 8, "occurrence" : 4, "win" : 10},                 
	      {"id" : 26, "symbol" : 8, "occurrence" : 3, "win" : 5},                 
	      {"id" : 27, "symbol" : 9, "occurrence" : 5, "win" : 30},                 
	      {"id" : 28, "symbol" : 9, "occurrence" : 4, "win" : 10},                 
	      {"id" : 29, "symbol" : 9, "occurrence" : 3, "win" : 5},  
	      {"id" : 30, "symbol" : 3, "occurrence" : 3, "win" : 300, "line" : 4},
	      {"id" : 31, "symbol" : 5, "occurrence" : 3, "win" : 1000, "coins" : 20}
	 ]
}